In [46]:
import pandas as pd
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np 
import seaborn as sns

In [47]:
df=pd.read_csv('data.csv')

In [48]:
df.head()

,feature1,feature2,feature3,target
0,-0.570563,1.420342,0.495580,-9.763182
1,-0.990563,0.556965,1.045064,-24.029355
2,-0.674728,0.150617,1.774645,45.616421
3,0.388250,-0.387127,-0.110229,34.135737
4,1.167882,-0.024104,0.145063,86.663647


In [49]:
x=df.iloc[:,0:3].values
y=df.iloc[:,-1].values

In [50]:
x.shape

(200, 3)

In [51]:
y.shape

(200,)

In [52]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.3,random_state=1)

In [53]:
x_train.shape

(60, 3)

In [54]:
y_train.shape

(60,)

In [55]:
lr=LinearRegression()

In [56]:
lr.fit(x_train,y_train)

LinearRegression()

In [70]:
x_test[0]

array([-0.83423985,  1.34499246,  0.48624933])

In [81]:
y_test[4]

98.69333864552068

In [80]:
lr.predict(x_test[4:5])

array([112.10917517])

In [69]:
x_test

array([[-0.83423985,  1.34499246,  0.48624933],
       [ 0.62747389, -0.05394785,  2.71192633],
       [ 0.12800782,  1.24161652,  0.08841521],
       [-0.4129564 ,  1.27727436,  0.25622178],
       [ 1.86950756,  0.66590511, -0.33750905],
       [-0.9148222 , -0.89713978, -0.78420535],
       [-0.41619802,  0.72465766, -0.18907167],
       [ 1.16788229, -0.02410447,  0.14506321],
       [-0.38466318,  0.04365869,  0.38033506],
       [ 0.13801466,  0.93950285,  0.34379452],
       [ 0.73146574,  0.42596675, -0.7160258 ],
       [-1.3580452 , -0.06711047, -0.16943686],
       [ 1.11594518, -0.03030337, -0.31959014],
       [ 0.69405227, -0.51112899,  1.72941743],
       [-0.27273554, -2.67652137, -0.04184423],
       [ 1.6265736 , -1.41987131,  0.35081584],
       [-1.0259683 , -1.89787143,  0.43175699],
       [ 2.45758763,  1.06721555, -0.19829026],
       [-0.15851092, -1.05080794,  1.34407129],
       [ 0.87428572, -1.29353663,  2.15814934],
       [ 1.07168393, -1.22090192, -0.862

In [84]:

# Residual
y_pred = lr.predict(x_test)
residual = y_test - y_pred